ghdl -a code_memory.vhd
ghdl -a IF_stage.vhd
ghdl -a IF_ID.vhd
ghdl -a priority_encoder.vhd
ghdl -a HDU.vhd
ghdl -a ControlSignals.vhd
ghdl -a ID_stage.vhd
ghdl -a ID_RR.vhd
ghdl -a decoder.vhd
ghdl -a encoder1.vhd
ghdl -a RF.vhd
ghdl -a RFComplete.vhd
ghdl -a RR.vhd
ghdl -a RR_EX.vhd
ghdl -a ALU.vhd
ghdl -a ALU_2.vhd
ghdl -a ForwardUnit.vhd
ghdl -a EX_entity.vhd
ghdl -a EX_MA.vhd
ghdl -a data_memory.vhd
ghdl -a MA.vhd
ghdl -a MA_WB.vhd
ghdl -a WB_entity.vhd
ghdl -a Microprocessor.vhd
